#!/bin/bash

echo "🚀 Déploiement de Mentality Web sur GitHub"
echo "==========================================="
echo ""
echo "✅ Git est configuré pour: alvin kuyo (loup.partner@gmail.com)"
echo "✅ Repository local prêt avec 2 commits"
echo "✅ Remote configuré: https://github.com/alvinkuyo/mentality-web.git"
echo ""
echo "📝 Prochaines étapes:"
echo ""
echo "1️⃣  Créez le repository sur GitHub (si pas encore fait):"
echo "    👉 Allez sur: https://github.com/new"
echo "    📝 Nom: mentality-web"
echo "    🔓 Public"
echo "    ⚠️  N'ajoutez PAS de README, .gitignore ou license"
echo "    ✅ Cliquez sur 'Create repository'"
echo ""
echo "2️⃣  Poussez le code avec cette commande:"
echo ""
echo "    git push -u origin main"
echo ""
echo "    GitHub vous demandera vos credentials:"
echo "    - Username: votre username GitHub (probablement: alvinkuyo)"
echo "    - Password: utilisez un PERSONAL ACCESS TOKEN (pas votre mot de passe!)"
echo ""
echo "3️⃣  Si vous n'avez pas de Personal Access Token:"
echo "    👉 https://github.com/settings/tokens"
echo "    ➕ Generate new token (classic)"
echo "    📝 Name: mentality-web-deploy"
echo "    ☑️  Scope: 'repo' (cochez tout)"
echo "    💾 Generate token"
echo "    📋 COPIEZ LE TOKEN (vous ne pourrez plus le voir!)"
echo ""
echo "4️⃣  Activez GitHub Pages:"
echo "    👉 https://github.com/alvinkuyo/mentality-web/settings/pages"
echo "    📁 Source: 'GitHub Actions'"
echo "    💾 Save"
echo ""
echo "5️⃣  Attendez 2-3 minutes, puis visitez:"
echo "    🌐 https://alvinkuyo.github.io/mentality-web/"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "💡 Astuce: Si vous avez déjà un token ou SSH configuré,"
echo "           lancez simplement:"
echo ""
echo "           cd \"/Users/alvinkuyo/Downloads/Mentality copie/mentality-web\""
echo "           git push -u origin main"
echo ""
echo "═══════════════════════════════════════════════════════════"
